import { expect, test, type APIRequestContext, type Page } from "@playwright/test";

import { createE2EUserWithRoles } from "./helpers/api";

type ClientErrors = {
  pageErrors: string[];
  consoleErrors: string[];
};

function collectClientErrors(page: Page): ClientErrors {
  const pageErrors: string[] = [];
  const consoleErrors: string[] = [];

  page.on("pageerror", (error) => {
    pageErrors.push(String(error));
  });
  page.on("console", (message) => {
    if (message.type() === "error") {
      consoleErrors.push(message.text());
    }
  });

  return { pageErrors, consoleErrors };
}

async function assertNoClientErrors(errors: ClientErrors): Promise<void> {
  await expect(errors.pageErrors, `Unexpected page errors: ${errors.pageErrors.join(" | ")}`).toEqual([]);
  await expect(errors.consoleErrors, `Unexpected console errors: ${errors.consoleErrors.join(" | ")}`).toEqual([]);
}

async function loginApi(request: APIRequestContext, username: string, password: string): Promise<string> {
  const response = await request.post("/api/auth/login", {
    data: { username, password },
  });
  expect(response.ok()).toBeTruthy();
  const payload = (await response.json()) as { access_token: string };
  return payload.access_token;
}

async function ensureProductGroup(request: APIRequestContext, token: string, groupName: string): Promise<void> {
  const headers = { Authorization: `Bearer ${token}` };
  const listResponse = await request.get("/api/product-groups", { headers });
  expect(listResponse.ok()).toBeTruthy();
  const groups = (await listResponse.json()) as Array<{ id: number; name: string }>;
  if (groups.some((group) => group.name === groupName)) {
    return;
  }

  const createResponse = await request.post("/api/product-groups", {
    headers,
    data: {
      name: groupName,
      description: `E2E product-form group ${groupName}`,
    },
  });
  if (!createResponse.ok()) {
    expect(createResponse.status()).toBe(409);
  }
}

async function loginAndOpenProductCreatePage(page: Page, username: string, password: string): Promise<void> {
  await page.goto("/login");
  await page.getByTestId("login-username").fill(username);
  await page.getByTestId("login-password").fill(password);
  await page.getByTestId("login-submit").click();
  await expect(page).toHaveURL(/\/dashboard$/);

  await page.goto("/products/new");
  await expect(page).toHaveURL(/\/products\/new$/);
  await expect(page.getByTestId("product-form-page")).toBeVisible();
}

test.describe("product form create wizard flow", () => {
  test("creates product, continues through wizard steps and finishes", async ({ page, request }) => {
    const errors = collectClientErrors(page);
    const user = await createE2EUserWithRoles(request, ["admin"]);
    const token = await loginApi(request, user.username, user.password);
    const marker = `${Date.now()}${Math.floor(Math.random() * 10_000)
      .toString()
      .padStart(4, "0")}`;
    const groupName = `E2E-PF-GROUP-${marker}`;

    await ensureProductGroup(request, token, groupName);
    await loginAndOpenProductCreatePage(page, user.username, user.password);
    await expect(page.getByTestId("product-create-stepper")).toBeVisible();
    await expect(page.getByTestId("product-create-step-master")).toBeVisible();

    await page.getByTestId("product-form-number").fill(`E2E-PF-${marker}`);
    await page.getByTestId("product-form-name").fill(`E2E Product Form ${marker}`);
    await page.getByTestId("product-form-description").fill(`Generated by playwright ${marker}`);
    await page.getByTestId("product-form-unit").fill("piece");
    await page.getByTestId("product-form-status").selectOption("active");
    await page.getByRole("button", { name: /Keine Gruppe|E2E-PF-GROUP/ }).first().click();
    await page.getByRole("button", { name: groupName }).click();

    await page.getByTestId("product-form-submit").click();

    await expect(page).toHaveURL(/\/products\/\d+\/edit\?flow=create&step=pricing$/);
    await expect(page.getByTestId("product-create-stepper")).toBeVisible();
    await expect(page.getByTestId("product-form-pricing-panel")).toBeVisible();

    await expect(page.getByTestId("product-pricing-net-input")).toBeVisible();
    await expect(page.getByTestId("product-pricing-vat-select")).toBeVisible();
    await expect(page.getByTestId("product-pricing-gross-preview")).toBeVisible();
    await expect(page.getByTestId("product-pricing-save-btn")).toBeVisible();
    await expect(page.getByTestId("product-pricing-history")).toBeVisible();

    await page.getByTestId("product-pricing-net-input").fill("10.00");
    await page.getByTestId("product-pricing-vat-select").selectOption("19");
    await expect(page.getByTestId("product-pricing-gross-preview")).toContainText("11.90 EUR");
    await page.getByTestId("product-pricing-save-btn").click();

    await expect(page.getByTestId("product-pricing-history")).toContainText("10.00 EUR");
    await expect(page.getByTestId("product-pricing-history")).toContainText("19.00%");
    await expect(page.getByTestId("product-pricing-history")).toContainText("11.90 EUR");

    await page.getByTestId("product-create-next").click();
    await expect(page).toHaveURL(/\/products\/\d+\/edit\?flow=create&step=warehouse$/);
    await expect(page.getByTestId("product-form-warehouse-tab")).toBeVisible();

    await page.reload();
    await expect(page).toHaveURL(/\/products\/\d+\/edit\?flow=create&step=warehouse$/);
    await expect(page.getByTestId("product-form-warehouse-tab")).toBeVisible();

    await page.getByTestId("product-create-skip").click();
    await expect(page).toHaveURL(/\/products\/\d+\/edit\?flow=create&step=suppliers$/);
    await expect(page.getByTestId("product-form-suppliers-tab")).toBeVisible();
    await expect(page.getByTestId("product-create-finish")).toBeVisible();

    await page.getByTestId("product-create-finish").click();
    await expect(page).toHaveURL(/\/products\/\d+$/);

    await assertNoClientErrors(errors);
  });
});
