import {
  AlertCircle,
  ArrowDownToLine,
  ArrowRightLeft,
  ArrowUpFromLine,
  BarChart3,
  Building2,
  CheckSquare,
  ClipboardList,
  Combine,
  Factory,
  FileSpreadsheet,
  FileText,
  History,
  LayoutDashboard,
  Package,
  Receipt,
  RotateCcw,
  ScanBarcode,
  ShoppingCart,
  Truck,
  Users,
  Warehouse,
} from "lucide-react";

import {
  AlertsPage,
  ApprovalsPage,
  AuditTrailPage,
  CustomersPage,
  DashboardPage,
  DocumentsPage,
  GoodsIssuePage,
  GoodsReceiptPage,
  InterWarehouseTransferPage,
  InventoryCountPage,
  InventoryPage,
  InvoicesPage,
  PickingPage,
  ProductDetailPage,
  ProductFormPage,
  ProductsPage,
  PurchasingPage,
  ReportsPage,
  ReturnsPage,
  SalesOrdersPage,
  ScannerPage,
  ShippingPage,
  StockTransferPage,
  SuppliersPage,
  UsersPage,
  WarehousePage,
} from "../pages";
import type { AppRouteDefinition } from "./routeTypes";

export const routeCatalogEntries: AppRouteDefinition[] = [
  {
    path: "/dashboard",
    pageSlug: "dashboard",
    requiredPermission: "page.dashboard.view",
    navLabel: "Dashboard",
    shortLabel: "DB",
    icon: LayoutDashboard,
    showInNav: true,
    priority: 10,
    component: DashboardPage,
  },
  {
    path: "/products",
    pageSlug: "products",
    requiredPermission: "page.products.view",
    navLabel: "Artikelstamm",
    shortLabel: "AR",
    icon: Package,
    showInNav: true,
    priority: 20,
    component: ProductsPage,
  },
  {
    path: "/products/new",
    pageSlug: "products",
    requiredPermission: "page.products.view",
    navLabel: "Artikelstamm",
    shortLabel: "AR",
    icon: Package,
    showInNav: false,
    priority: 21,
    component: ProductFormPage,
    title: "Artikelstamm / Neu",
  },
  {
    path: "/products/:id",
    pageSlug: "products",
    requiredPermission: "page.products.view",
    navLabel: "Artikelstamm",
    shortLabel: "AR",
    icon: Package,
    showInNav: false,
    priority: 22,
    component: ProductDetailPage,
    title: "Artikelstamm / Details",
  },
  {
    path: "/products/:id/edit",
    pageSlug: "products",
    requiredPermission: "page.products.view",
    navLabel: "Artikelstamm",
    shortLabel: "AR",
    icon: Package,
    showInNav: false,
    priority: 23,
    component: ProductFormPage,
    title: "Artikelstamm / Bearbeiten",
  },
  {
    path: "/warehouse",
    pageSlug: "warehouse",
    requiredPermission: "page.warehouse.view",
    navLabel: "Lagerstruktur",
    shortLabel: "LG",
    icon: Factory,
    showInNav: true,
    priority: 30,
    component: WarehousePage,
  },
  {
    path: "/inventory",
    pageSlug: "inventory",
    requiredPermission: "page.inventory.view",
    navLabel: "Bestandsübersicht",
    shortLabel: "BS",
    icon: Combine,
    showInNav: true,
    priority: 40,
    component: InventoryPage,
  },
  {
    path: "/inventory-counts",
    pageSlug: "inventory-counts",
    requiredPermission: "page.inventory-counts.view",
    navLabel: "Inventur",
    shortLabel: "IV",
    icon: ClipboardList,
    showInNav: true,
    priority: 50,
    component: InventoryCountPage,
  },
  {
    path: "/purchasing",
    pageSlug: "purchasing",
    requiredPermission: "page.purchasing.view",
    navLabel: "Einkauf",
    shortLabel: "EK",
    icon: ShoppingCart,
    showInNav: true,
    priority: 60,
    component: PurchasingPage,
  },
  {
    path: "/picking",
    pageSlug: "picking",
    requiredPermission: "page.picking.view",
    navLabel: "Kommissionierung",
    shortLabel: "PK",
    icon: CheckSquare,
    showInNav: true,
    priority: 70,
    component: PickingPage,
  },
  {
    path: "/returns",
    pageSlug: "returns",
    requiredPermission: "page.returns.view",
    navLabel: "Retouren",
    shortLabel: "RT",
    icon: RotateCcw,
    showInNav: true,
    priority: 80,
    component: ReturnsPage,
  },
  {
    path: "/approvals",
    pageSlug: "approvals",
    requiredPermission: "page.approvals.view",
    navLabel: "Genehmigungen",
    shortLabel: "GN",
    icon: CheckSquare,
    showInNav: true,
    priority: 90,
    component: ApprovalsPage,
  },
  {
    path: "/documents",
    pageSlug: "documents",
    requiredPermission: "page.documents.view",
    navLabel: "Dokumente",
    shortLabel: "DM",
    icon: FileText,
    showInNav: true,
    priority: 100,
    component: DocumentsPage,
  },
  {
    path: "/audit-trail",
    pageSlug: "audit-trail",
    requiredPermission: "page.audit-trail.view",
    navLabel: "Audit-Trail",
    shortLabel: "AT",
    icon: History,
    showInNav: true,
    priority: 110,
    component: AuditTrailPage,
  },
  {
    path: "/reports",
    pageSlug: "reports",
    requiredPermission: "page.reports.view",
    navLabel: "Berichte",
    shortLabel: "RP",
    icon: BarChart3,
    showInNav: true,
    priority: 120,
    component: ReportsPage,
  },
  {
    path: "/alerts",
    pageSlug: "alerts",
    requiredPermission: "page.alerts.view",
    navLabel: "Warnungen",
    shortLabel: "AL",
    icon: AlertCircle,
    showInNav: true,
    priority: 130,
    component: AlertsPage,
  },
  {
    path: "/goods-receipt",
    pageSlug: "goods-receipt",
    requiredPermission: "page.goods-receipt.view",
    navLabel: "Wareneingang",
    shortLabel: "WE",
    icon: ArrowDownToLine,
    showInNav: true,
    priority: 140,
    component: GoodsReceiptPage,
  },
  {
    path: "/goods-issue",
    pageSlug: "goods-issue",
    requiredPermission: "page.goods-issue.view",
    navLabel: "Warenausgang",
    shortLabel: "WA",
    icon: ArrowUpFromLine,
    showInNav: true,
    priority: 150,
    component: GoodsIssuePage,
  },
  {
    path: "/stock-transfer",
    pageSlug: "stock-transfer",
    requiredPermission: "page.stock-transfer.view",
    navLabel: "Umlagerung",
    shortLabel: "UM",
    icon: ArrowRightLeft,
    showInNav: true,
    priority: 160,
    component: StockTransferPage,
  },
  {
    path: "/inter-warehouse-transfer",
    pageSlug: "inter-warehouse-transfer",
    requiredPermission: "page.inter-warehouse-transfer.view",
    navLabel: "Zwischenlager",
    shortLabel: "IW",
    icon: Warehouse,
    showInNav: true,
    priority: 170,
    component: InterWarehouseTransferPage,
  },
  {
    path: "/shipping",
    pageSlug: "shipping",
    requiredPermission: "page.shipping.view",
    navLabel: "Versand",
    shortLabel: "SH",
    icon: Truck,
    showInNav: true,
    priority: 180,
    component: ShippingPage,
  },
  {
    path: "/customers",
    pageSlug: "customers",
    requiredPermission: "page.customers.view",
    navLabel: "Kunden",
    shortLabel: "KD",
    icon: Building2,
    showInNav: true,
    priority: 190,
    component: CustomersPage,
  },
  {
    path: "/suppliers",
    pageSlug: "suppliers",
    requiredPermission: "page.suppliers.view",
    navLabel: "Lieferanten",
    shortLabel: "LF",
    icon: Building2,
    showInNav: true,
    priority: 195,
    component: SuppliersPage,
  },
  {
    path: "/scanner",
    pageSlug: "scanner",
    requiredPermission: "page.scanner.view",
    navLabel: "Scanner",
    shortLabel: "SC",
    icon: ScanBarcode,
    showInNav: true,
    priority: 200,
    component: ScannerPage,
  },
  {
    path: "/sales-orders",
    pageSlug: "sales-orders",
    requiredPermission: "page.sales-orders.view",
    navLabel: "Verkaufsaufträge",
    shortLabel: "SO",
    icon: FileSpreadsheet,
    showInNav: true,
    priority: 210,
    component: SalesOrdersPage,
  },
  {
    path: "/invoices",
    pageSlug: "invoices",
    requiredPermission: "page.invoices.view",
    navLabel: "Rechnungen",
    shortLabel: "RE",
    icon: Receipt,
    showInNav: true,
    priority: 220,
    component: InvoicesPage,
  },
  {
    path: "/users",
    pageSlug: "users",
    requiredPermission: "page.users.view",
    navLabel: "Benutzerverwaltung",
    shortLabel: "BU",
    icon: Users,
    showInNav: true,
    priority: 230,
    component: UsersPage,
  },
];
