#!/usr/bin/env python3
from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from sqlalchemy import and_, create_engine, delete, false, func, or_, select
from sqlalchemy.orm import Session

ROOT = Path(__file__).resolve().parents[1]
BACKEND_DIR = ROOT / "backend"
if str(BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(BACKEND_DIR))

from app.config import get_settings
from app.models import (  # noqa: E402
    AbcClassificationItem,
    AbcClassificationRun,
    AlertEvent,
    AlertRule,
    ApprovalAction,
    ApprovalRequest,
    ApprovalRule,
    AuditLog,
    BinLocation,
    ClientOperationLog,
    Customer,
    CustomerContact,
    CustomerLocation,
    CustomerProductPrice,
    Document,
    ForecastItem,
    ForecastRun,
    GoodsIssue,
    GoodsIssueItem,
    GoodsReceipt,
    GoodsReceiptItem,
    IntegrationAccessLog,
    IntegrationClient,
    InterWarehouseTransfer,
    InterWarehouseTransferItem,
    Inventory,
    InventoryBatch,
    InventoryCountItem,
    InventoryCountSession,
    Invoice,
    InvoiceExport,
    InvoiceItem,
    PickTask,
    PickWave,
    Product,
    ProductBasePrice,
    ProductGroup,
    ProductSupplier,
    ProductWarehouseSetting,
    PurchaseOrder,
    PurchaseOrderItem,
    PurchaseRecommendation,
    ReturnOrder,
    ReturnOrderItem,
    Role,
    RoleDashboardPolicy,
    SalesOrder,
    SalesOrderGoodsIssueLink,
    SalesOrderItem,
    SerialNumber,
    Shipment,
    ShipmentEvent,
    StockMovement,
    StockTransfer,
    StockTransferItem,
    Supplier,
    User,
    UserDashboardConfig,
    UserUiPreference,
    Warehouse,
    WarehouseZone,
    role_permissions,
    user_roles,
)

PREFIX_PATTERNS = (
    "E2E-%",
    "000-E2E-%",
    "E2EIC%",
    "E2EZ%",
    "E2EB%",
    "e2e_%",
    "e2e-%",
)

CONTAINS_PATTERNS = (
    "%Playwright%",
    "%playwright%",
    "%E2E Gruppe%",
    "%e2e-doc%",
    "%audit-e2e-%",
    "%Generated by playwright%",
    "%E2E UI User%",
)


@dataclass(frozen=True)
class CleanupOp:
    label: str
    table: Any
    where_clause: Any
    id_column: Any | None = None


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="One-time cleanup for DirectStock E2E/test data")
    parser.add_argument("--mode", choices=["dry-run", "apply"], default="dry-run")
    parser.add_argument("--sample-size", type=int, default=5)
    return parser.parse_args()


def where_any(*clauses: Any) -> Any:
    valid = [clause for clause in clauses if clause is not None]
    if not valid:
        return false()
    if len(valid) == 1:
        return valid[0]
    return or_(*valid)


def marker_clause(*columns: Any) -> Any:
    clauses: list[Any] = []
    for column in columns:
        clauses.extend(column.ilike(pattern) for pattern in PREFIX_PATTERNS)
        clauses.extend(column.ilike(pattern) for pattern in CONTAINS_PATTERNS)
    return where_any(*clauses)


def in_ids(column: Any, ids: set[int]) -> Any:
    if not ids:
        return false()
    return column.in_(sorted(ids))


def id_set(session: Session, model: Any, clause: Any) -> set[int]:
    return set(session.scalars(select(model.id).where(clause)).all())


def count_rows(session: Session, table: Any, clause: Any) -> int:
    return int(session.scalar(select(func.count()).select_from(table).where(clause)) or 0)


def sample_ids(session: Session, id_column: Any, clause: Any, sample_size: int) -> list[int]:
    return list(session.scalars(select(id_column).where(clause).order_by(id_column).limit(sample_size)).all())


def collect_ids(session: Session) -> dict[str, set[int]]:
    ids: dict[str, set[int]] = {}

    ids["roles"] = id_set(session, Role, marker_clause(Role.name, Role.description))
    ids["users"] = id_set(session, User, marker_clause(User.username, User.email, User.full_name))
    ids["product_groups"] = id_set(
        session,
        ProductGroup,
        where_any(
            marker_clause(ProductGroup.name, ProductGroup.description),
            ProductGroup.name == "E2E Gruppe",
        ),
    )

    ids["products"] = id_set(
        session,
        Product,
        where_any(
            marker_clause(Product.product_number, Product.name, Product.description),
            in_ids(Product.product_group_id, ids["product_groups"]),
        ),
    )

    ids["suppliers"] = id_set(
        session,
        Supplier,
        marker_clause(Supplier.supplier_number, Supplier.company_name, Supplier.contact_name, Supplier.email),
    )
    ids["customers"] = id_set(
        session,
        Customer,
        marker_clause(Customer.customer_number, Customer.company_name, Customer.contact_name, Customer.email),
    )

    ids["warehouses"] = id_set(session, Warehouse, marker_clause(Warehouse.code, Warehouse.name, Warehouse.address))
    ids["warehouse_zones"] = id_set(
        session,
        WarehouseZone,
        where_any(
            marker_clause(WarehouseZone.code, WarehouseZone.name),
            in_ids(WarehouseZone.warehouse_id, ids["warehouses"]),
        ),
    )
    ids["bin_locations"] = id_set(
        session,
        BinLocation,
        where_any(
            marker_clause(BinLocation.code, BinLocation.qr_code_data),
            in_ids(BinLocation.zone_id, ids["warehouse_zones"]),
        ),
    )

    ids["customer_locations"] = id_set(
        session,
        CustomerLocation,
        where_any(
            marker_clause(
                CustomerLocation.location_code,
                CustomerLocation.name,
                CustomerLocation.email,
                CustomerLocation.street,
                CustomerLocation.city,
            ),
            in_ids(CustomerLocation.customer_id, ids["customers"]),
        ),
    )
    ids["customer_contacts"] = id_set(
        session,
        CustomerContact,
        where_any(
            marker_clause(
                CustomerContact.first_name,
                CustomerContact.last_name,
                CustomerContact.email,
                CustomerContact.notes,
            ),
            in_ids(CustomerContact.customer_id, ids["customers"]),
            in_ids(CustomerContact.customer_location_id, ids["customer_locations"]),
        ),
    )

    ids["purchase_orders"] = id_set(
        session,
        PurchaseOrder,
        where_any(
            in_ids(PurchaseOrder.supplier_id, ids["suppliers"]),
            in_ids(PurchaseOrder.created_by, ids["users"]),
            marker_clause(PurchaseOrder.notes),
        ),
    )
    ids["purchase_order_items"] = id_set(
        session,
        PurchaseOrderItem,
        where_any(
            in_ids(PurchaseOrderItem.purchase_order_id, ids["purchase_orders"]),
            in_ids(PurchaseOrderItem.product_id, ids["products"]),
        ),
    )

    ids["goods_receipts"] = id_set(
        session,
        GoodsReceipt,
        where_any(
            in_ids(GoodsReceipt.supplier_id, ids["suppliers"]),
            in_ids(GoodsReceipt.purchase_order_id, ids["purchase_orders"]),
            in_ids(GoodsReceipt.created_by, ids["users"]),
            marker_clause(GoodsReceipt.notes),
        ),
    )
    ids["goods_receipt_items"] = id_set(
        session,
        GoodsReceiptItem,
        where_any(
            in_ids(GoodsReceiptItem.goods_receipt_id, ids["goods_receipts"]),
            in_ids(GoodsReceiptItem.product_id, ids["products"]),
            in_ids(GoodsReceiptItem.target_bin_id, ids["bin_locations"]),
            in_ids(GoodsReceiptItem.purchase_order_item_id, ids["purchase_order_items"]),
            marker_clause(GoodsReceiptItem.batch_number),
        ),
    )

    ids["goods_issues"] = id_set(
        session,
        GoodsIssue,
        where_any(
            in_ids(GoodsIssue.customer_id, ids["customers"]),
            in_ids(GoodsIssue.customer_location_id, ids["customer_locations"]),
            in_ids(GoodsIssue.created_by, ids["users"]),
            marker_clause(GoodsIssue.notes, GoodsIssue.customer_reference),
        ),
    )
    ids["goods_issue_items"] = id_set(
        session,
        GoodsIssueItem,
        where_any(
            in_ids(GoodsIssueItem.goods_issue_id, ids["goods_issues"]),
            in_ids(GoodsIssueItem.product_id, ids["products"]),
            in_ids(GoodsIssueItem.source_bin_id, ids["bin_locations"]),
            marker_clause(GoodsIssueItem.batch_number),
        ),
    )

    ids["stock_transfers"] = id_set(
        session,
        StockTransfer,
        where_any(
            in_ids(StockTransfer.created_by, ids["users"]),
            marker_clause(StockTransfer.notes),
        ),
    )
    ids["stock_transfer_items"] = id_set(
        session,
        StockTransferItem,
        where_any(
            in_ids(StockTransferItem.stock_transfer_id, ids["stock_transfers"]),
            in_ids(StockTransferItem.product_id, ids["products"]),
            in_ids(StockTransferItem.from_bin_id, ids["bin_locations"]),
            in_ids(StockTransferItem.to_bin_id, ids["bin_locations"]),
            marker_clause(StockTransferItem.batch_number),
        ),
    )

    ids["inter_warehouse_transfers"] = id_set(
        session,
        InterWarehouseTransfer,
        where_any(
            in_ids(InterWarehouseTransfer.from_warehouse_id, ids["warehouses"]),
            in_ids(InterWarehouseTransfer.to_warehouse_id, ids["warehouses"]),
            in_ids(InterWarehouseTransfer.created_by, ids["users"]),
            marker_clause(InterWarehouseTransfer.notes),
        ),
    )
    ids["inter_warehouse_transfer_items"] = id_set(
        session,
        InterWarehouseTransferItem,
        where_any(
            in_ids(
                InterWarehouseTransferItem.inter_warehouse_transfer_id,
                ids["inter_warehouse_transfers"],
            ),
            in_ids(InterWarehouseTransferItem.product_id, ids["products"]),
            in_ids(InterWarehouseTransferItem.from_bin_id, ids["bin_locations"]),
            in_ids(InterWarehouseTransferItem.to_bin_id, ids["bin_locations"]),
            marker_clause(InterWarehouseTransferItem.batch_number),
        ),
    )

    ids["return_orders"] = id_set(
        session,
        ReturnOrder,
        where_any(
            in_ids(ReturnOrder.customer_id, ids["customers"]),
            in_ids(ReturnOrder.goods_issue_id, ids["goods_issues"]),
            in_ids(ReturnOrder.created_by, ids["users"]),
            marker_clause(ReturnOrder.notes, ReturnOrder.source_reference),
        ),
    )
    ids["return_order_items"] = id_set(
        session,
        ReturnOrderItem,
        where_any(
            in_ids(ReturnOrderItem.return_order_id, ids["return_orders"]),
            in_ids(ReturnOrderItem.product_id, ids["products"]),
            in_ids(ReturnOrderItem.target_bin_id, ids["bin_locations"]),
            marker_clause(ReturnOrderItem.reason),
        ),
    )

    ids["pick_waves"] = id_set(
        session,
        PickWave,
        where_any(
            in_ids(PickWave.created_by, ids["users"]),
            marker_clause(PickWave.notes),
        ),
    )
    ids["pick_tasks"] = id_set(
        session,
        PickTask,
        where_any(
            in_ids(PickTask.pick_wave_id, ids["pick_waves"]),
            in_ids(PickTask.goods_issue_id, ids["goods_issues"]),
            in_ids(PickTask.goods_issue_item_id, ids["goods_issue_items"]),
            in_ids(PickTask.product_id, ids["products"]),
            in_ids(PickTask.source_bin_id, ids["bin_locations"]),
            in_ids(PickTask.picked_by, ids["users"]),
        ),
    )

    ids["sales_orders"] = id_set(
        session,
        SalesOrder,
        where_any(
            in_ids(SalesOrder.customer_id, ids["customers"]),
            in_ids(SalesOrder.customer_location_id, ids["customer_locations"]),
            in_ids(SalesOrder.created_by, ids["users"]),
            marker_clause(SalesOrder.notes),
        ),
    )
    ids["sales_order_items"] = id_set(
        session,
        SalesOrderItem,
        where_any(
            in_ids(SalesOrderItem.sales_order_id, ids["sales_orders"]),
            in_ids(SalesOrderItem.product_id, ids["products"]),
            marker_clause(SalesOrderItem.description),
        ),
    )
    ids["sales_order_goods_issue_links"] = id_set(
        session,
        SalesOrderGoodsIssueLink,
        where_any(
            in_ids(SalesOrderGoodsIssueLink.sales_order_id, ids["sales_orders"]),
            in_ids(SalesOrderGoodsIssueLink.goods_issue_id, ids["goods_issues"]),
        ),
    )

    ids["invoices"] = id_set(
        session,
        Invoice,
        where_any(
            in_ids(Invoice.sales_order_id, ids["sales_orders"]),
            in_ids(Invoice.created_by, ids["users"]),
            marker_clause(Invoice.notes),
        ),
    )
    ids["invoice_items"] = id_set(
        session,
        InvoiceItem,
        where_any(
            in_ids(InvoiceItem.invoice_id, ids["invoices"]),
            in_ids(InvoiceItem.sales_order_item_id, ids["sales_order_items"]),
            marker_clause(InvoiceItem.description),
        ),
    )
    ids["invoice_exports"] = id_set(
        session,
        InvoiceExport,
        in_ids(InvoiceExport.invoice_id, ids["invoices"]),
    )

    ids["shipments"] = id_set(
        session,
        Shipment,
        where_any(
            in_ids(Shipment.goods_issue_id, ids["goods_issues"]),
            in_ids(Shipment.customer_id, ids["customers"]),
            in_ids(Shipment.customer_location_id, ids["customer_locations"]),
            in_ids(Shipment.created_by, ids["users"]),
            marker_clause(Shipment.tracking_number, Shipment.recipient_name, Shipment.shipping_address),
        ),
    )
    ids["shipment_events"] = id_set(
        session,
        ShipmentEvent,
        where_any(
            in_ids(ShipmentEvent.shipment_id, ids["shipments"]),
            in_ids(ShipmentEvent.created_by, ids["users"]),
            marker_clause(ShipmentEvent.description, ShipmentEvent.source),
        ),
    )

    ids["alert_rules"] = id_set(
        session,
        AlertRule,
        where_any(
            in_ids(AlertRule.product_id, ids["products"]),
            in_ids(AlertRule.warehouse_id, ids["warehouses"]),
            marker_clause(AlertRule.name),
        ),
    )
    ids["alert_events"] = id_set(
        session,
        AlertEvent,
        where_any(
            in_ids(AlertEvent.rule_id, ids["alert_rules"]),
            in_ids(AlertEvent.product_id, ids["products"]),
            in_ids(AlertEvent.warehouse_id, ids["warehouses"]),
            in_ids(AlertEvent.bin_location_id, ids["bin_locations"]),
            in_ids(AlertEvent.acknowledged_by, ids["users"]),
            marker_clause(AlertEvent.title, AlertEvent.message, AlertEvent.source_key),
        ),
    )

    ids["inventory_count_sessions"] = id_set(
        session,
        InventoryCountSession,
        where_any(
            in_ids(InventoryCountSession.warehouse_id, ids["warehouses"]),
            in_ids(InventoryCountSession.created_by, ids["users"]),
            marker_clause(InventoryCountSession.notes, InventoryCountSession.session_number),
        ),
    )
    ids["inventory_count_items"] = id_set(
        session,
        InventoryCountItem,
        where_any(
            in_ids(InventoryCountItem.session_id, ids["inventory_count_sessions"]),
            in_ids(InventoryCountItem.product_id, ids["products"]),
            in_ids(InventoryCountItem.bin_location_id, ids["bin_locations"]),
        ),
    )

    ids["inventory"] = id_set(
        session,
        Inventory,
        where_any(
            in_ids(Inventory.product_id, ids["products"]),
            in_ids(Inventory.bin_location_id, ids["bin_locations"]),
        ),
    )
    ids["inventory_batches"] = id_set(
        session,
        InventoryBatch,
        where_any(
            in_ids(InventoryBatch.product_id, ids["products"]),
            in_ids(InventoryBatch.bin_location_id, ids["bin_locations"]),
            marker_clause(InventoryBatch.batch_number),
        ),
    )
    ids["serial_numbers"] = id_set(
        session,
        SerialNumber,
        where_any(
            in_ids(SerialNumber.product_id, ids["products"]),
            in_ids(SerialNumber.current_bin_id, ids["bin_locations"]),
            in_ids(SerialNumber.batch_id, ids["inventory_batches"]),
            marker_clause(SerialNumber.serial_number),
        ),
    )

    ids["stock_movements"] = id_set(
        session,
        StockMovement,
        where_any(
            in_ids(StockMovement.product_id, ids["products"]),
            in_ids(StockMovement.from_bin_id, ids["bin_locations"]),
            in_ids(StockMovement.to_bin_id, ids["bin_locations"]),
            in_ids(StockMovement.performed_by, ids["users"]),
            marker_clause(StockMovement.reference_number),
        ),
    )

    ids["purchase_recommendations"] = id_set(
        session,
        PurchaseRecommendation,
        where_any(
            in_ids(PurchaseRecommendation.product_id, ids["products"]),
            in_ids(PurchaseRecommendation.warehouse_id, ids["warehouses"]),
            in_ids(PurchaseRecommendation.supplier_id, ids["suppliers"]),
            in_ids(PurchaseRecommendation.generated_by, ids["users"]),
        ),
    )

    ids["abc_classification_items"] = id_set(
        session,
        AbcClassificationItem,
        in_ids(AbcClassificationItem.product_id, ids["products"]),
    )
    abc_run_ids_from_items = set(
        session.scalars(
            select(AbcClassificationItem.run_id).where(
                in_ids(AbcClassificationItem.id, ids["abc_classification_items"])
            )
        ).all()
    )
    ids["abc_classification_runs"] = id_set(
        session,
        AbcClassificationRun,
        where_any(
            in_ids(AbcClassificationRun.generated_by, ids["users"]),
            in_ids(AbcClassificationRun.id, abc_run_ids_from_items),
        ),
    )

    ids["forecast_items"] = id_set(
        session,
        ForecastItem,
        where_any(
            in_ids(ForecastItem.product_id, ids["products"]),
            in_ids(ForecastItem.warehouse_id, ids["warehouses"]),
        ),
    )
    forecast_run_ids_from_items = set(
        session.scalars(select(ForecastItem.run_id).where(in_ids(ForecastItem.id, ids["forecast_items"]))).all()
    )
    ids["forecast_runs"] = id_set(
        session,
        ForecastRun,
        where_any(
            in_ids(ForecastRun.generated_by, ids["users"]),
            in_ids(ForecastRun.id, forecast_run_ids_from_items),
            marker_clause(ForecastRun.notes),
        ),
    )

    ids["approval_rules"] = id_set(
        session,
        ApprovalRule,
        marker_clause(ApprovalRule.name, ApprovalRule.required_role),
    )
    ids["approval_requests"] = id_set(
        session,
        ApprovalRequest,
        where_any(
            in_ids(ApprovalRequest.requested_by, ids["users"]),
            in_ids(ApprovalRequest.decided_by, ids["users"]),
            marker_clause(ApprovalRequest.reason),
            and_(
                ApprovalRequest.entity_type == "purchase_order",
                in_ids(ApprovalRequest.entity_id, ids["purchase_orders"]),
            ),
            and_(
                ApprovalRequest.entity_type == "return_order",
                in_ids(ApprovalRequest.entity_id, ids["return_orders"]),
            ),
        ),
    )
    ids["approval_actions"] = id_set(
        session,
        ApprovalAction,
        where_any(
            in_ids(ApprovalAction.approval_request_id, ids["approval_requests"]),
            in_ids(ApprovalAction.acted_by, ids["users"]),
        ),
    )

    ids["product_suppliers"] = id_set(
        session,
        ProductSupplier,
        where_any(
            in_ids(ProductSupplier.product_id, ids["products"]),
            in_ids(ProductSupplier.supplier_id, ids["suppliers"]),
            marker_clause(ProductSupplier.supplier_product_number),
        ),
    )
    ids["product_warehouse_settings"] = id_set(
        session,
        ProductWarehouseSetting,
        where_any(
            in_ids(ProductWarehouseSetting.product_id, ids["products"]),
            in_ids(ProductWarehouseSetting.warehouse_id, ids["warehouses"]),
            marker_clause(ProductWarehouseSetting.qr_code_data),
        ),
    )
    ids["product_base_prices"] = id_set(
        session,
        ProductBasePrice,
        in_ids(ProductBasePrice.product_id, ids["products"]),
    )
    ids["customer_product_prices"] = id_set(
        session,
        CustomerProductPrice,
        where_any(
            in_ids(CustomerProductPrice.product_id, ids["products"]),
            in_ids(CustomerProductPrice.customer_id, ids["customers"]),
        ),
    )

    ids["user_dashboard_configs"] = id_set(
        session,
        UserDashboardConfig,
        in_ids(UserDashboardConfig.user_id, ids["users"]),
    )
    ids["user_ui_preferences"] = id_set(
        session,
        UserUiPreference,
        in_ids(UserUiPreference.user_id, ids["users"]),
    )
    ids["role_dashboard_policies"] = id_set(
        session,
        RoleDashboardPolicy,
        in_ids(RoleDashboardPolicy.role_id, ids["roles"]),
    )

    ids["integration_clients"] = id_set(
        session,
        IntegrationClient,
        where_any(
            in_ids(IntegrationClient.created_by, ids["users"]),
            marker_clause(IntegrationClient.name, IntegrationClient.client_id, IntegrationClient.notes),
        ),
    )
    ids["integration_access_logs"] = id_set(
        session,
        IntegrationAccessLog,
        where_any(
            in_ids(IntegrationAccessLog.integration_client_id, ids["integration_clients"]),
            marker_clause(IntegrationAccessLog.endpoint),
        ),
    )

    document_entity_clause = where_any(
        and_(Document.entity_type.in_(["invoice", "invoices"]), in_ids(Document.entity_id, ids["invoices"])),
        and_(
            Document.entity_type.in_(["sales_order", "sales_orders"]),
            in_ids(Document.entity_id, ids["sales_orders"]),
        ),
        and_(
            Document.entity_type.in_(["shipment", "shipments"]),
            in_ids(Document.entity_id, ids["shipments"]),
        ),
        and_(
            Document.entity_type.in_(["goods_issue", "goods_issues"]),
            in_ids(Document.entity_id, ids["goods_issues"]),
        ),
        and_(
            Document.entity_type.in_(["goods_receipt", "goods_receipts"]),
            in_ids(Document.entity_id, ids["goods_receipts"]),
        ),
    )
    ids["documents"] = id_set(
        session,
        Document,
        where_any(
            in_ids(Document.uploaded_by, ids["users"]),
            marker_clause(Document.file_name, Document.storage_path, Document.document_type),
            document_entity_clause,
        ),
    )

    ids["audit_logs"] = id_set(
        session,
        AuditLog,
        where_any(
            in_ids(AuditLog.user_id, ids["users"]),
            marker_clause(AuditLog.endpoint, AuditLog.entity, AuditLog.entity_id, AuditLog.request_id, AuditLog.error_message),
        ),
    )
    ids["client_operation_log"] = id_set(
        session,
        ClientOperationLog,
        marker_clause(ClientOperationLog.operation_id, ClientOperationLog.endpoint),
    )

    return ids


def build_operations(ids: dict[str, set[int]]) -> list[CleanupOp]:
    ops = [
        CleanupOp("integration_access_logs", IntegrationAccessLog, in_ids(IntegrationAccessLog.id, ids["integration_access_logs"]), IntegrationAccessLog.id),
        CleanupOp("audit_log", AuditLog, in_ids(AuditLog.id, ids["audit_logs"]), AuditLog.id),
        CleanupOp("client_operation_log", ClientOperationLog, in_ids(ClientOperationLog.id, ids["client_operation_log"]), ClientOperationLog.id),
        CleanupOp("approval_actions", ApprovalAction, in_ids(ApprovalAction.id, ids["approval_actions"]), ApprovalAction.id),
        CleanupOp("approval_requests", ApprovalRequest, in_ids(ApprovalRequest.id, ids["approval_requests"]), ApprovalRequest.id),
        CleanupOp("approval_rules", ApprovalRule, in_ids(ApprovalRule.id, ids["approval_rules"]), ApprovalRule.id),
        CleanupOp("invoice_exports", InvoiceExport, in_ids(InvoiceExport.id, ids["invoice_exports"]), InvoiceExport.id),
        CleanupOp("invoice_items", InvoiceItem, in_ids(InvoiceItem.id, ids["invoice_items"]), InvoiceItem.id),
        CleanupOp("invoices", Invoice, in_ids(Invoice.id, ids["invoices"]), Invoice.id),
        CleanupOp(
            "sales_order_goods_issue_links",
            SalesOrderGoodsIssueLink,
            in_ids(SalesOrderGoodsIssueLink.id, ids["sales_order_goods_issue_links"]),
            SalesOrderGoodsIssueLink.id,
        ),
        CleanupOp("sales_order_items", SalesOrderItem, in_ids(SalesOrderItem.id, ids["sales_order_items"]), SalesOrderItem.id),
        CleanupOp("sales_orders", SalesOrder, in_ids(SalesOrder.id, ids["sales_orders"]), SalesOrder.id),
        CleanupOp("shipment_events", ShipmentEvent, in_ids(ShipmentEvent.id, ids["shipment_events"]), ShipmentEvent.id),
        CleanupOp("shipments", Shipment, in_ids(Shipment.id, ids["shipments"]), Shipment.id),
        CleanupOp("pick_tasks", PickTask, in_ids(PickTask.id, ids["pick_tasks"]), PickTask.id),
        CleanupOp("pick_waves", PickWave, in_ids(PickWave.id, ids["pick_waves"]), PickWave.id),
        CleanupOp("return_order_items", ReturnOrderItem, in_ids(ReturnOrderItem.id, ids["return_order_items"]), ReturnOrderItem.id),
        CleanupOp("return_orders", ReturnOrder, in_ids(ReturnOrder.id, ids["return_orders"]), ReturnOrder.id),
        CleanupOp(
            "inter_warehouse_transfer_items",
            InterWarehouseTransferItem,
            in_ids(InterWarehouseTransferItem.id, ids["inter_warehouse_transfer_items"]),
            InterWarehouseTransferItem.id,
        ),
        CleanupOp(
            "inter_warehouse_transfers",
            InterWarehouseTransfer,
            in_ids(InterWarehouseTransfer.id, ids["inter_warehouse_transfers"]),
            InterWarehouseTransfer.id,
        ),
        CleanupOp("stock_transfer_items", StockTransferItem, in_ids(StockTransferItem.id, ids["stock_transfer_items"]), StockTransferItem.id),
        CleanupOp("stock_transfers", StockTransfer, in_ids(StockTransfer.id, ids["stock_transfers"]), StockTransfer.id),
        CleanupOp("goods_issue_items", GoodsIssueItem, in_ids(GoodsIssueItem.id, ids["goods_issue_items"]), GoodsIssueItem.id),
        CleanupOp("goods_issues", GoodsIssue, in_ids(GoodsIssue.id, ids["goods_issues"]), GoodsIssue.id),
        CleanupOp("goods_receipt_items", GoodsReceiptItem, in_ids(GoodsReceiptItem.id, ids["goods_receipt_items"]), GoodsReceiptItem.id),
        CleanupOp("goods_receipts", GoodsReceipt, in_ids(GoodsReceipt.id, ids["goods_receipts"]), GoodsReceipt.id),
        CleanupOp("purchase_order_items", PurchaseOrderItem, in_ids(PurchaseOrderItem.id, ids["purchase_order_items"]), PurchaseOrderItem.id),
        CleanupOp("purchase_orders", PurchaseOrder, in_ids(PurchaseOrder.id, ids["purchase_orders"]), PurchaseOrder.id),
        CleanupOp("inventory_count_items", InventoryCountItem, in_ids(InventoryCountItem.id, ids["inventory_count_items"]), InventoryCountItem.id),
        CleanupOp("inventory_count_sessions", InventoryCountSession, in_ids(InventoryCountSession.id, ids["inventory_count_sessions"]), InventoryCountSession.id),
        CleanupOp("alert_events", AlertEvent, in_ids(AlertEvent.id, ids["alert_events"]), AlertEvent.id),
        CleanupOp("alert_rules", AlertRule, in_ids(AlertRule.id, ids["alert_rules"]), AlertRule.id),
        CleanupOp("purchase_recommendations", PurchaseRecommendation, in_ids(PurchaseRecommendation.id, ids["purchase_recommendations"]), PurchaseRecommendation.id),
        CleanupOp("abc_classification_items", AbcClassificationItem, in_ids(AbcClassificationItem.id, ids["abc_classification_items"]), AbcClassificationItem.id),
        CleanupOp("abc_classification_runs", AbcClassificationRun, in_ids(AbcClassificationRun.id, ids["abc_classification_runs"]), AbcClassificationRun.id),
        CleanupOp("forecast_items", ForecastItem, in_ids(ForecastItem.id, ids["forecast_items"]), ForecastItem.id),
        CleanupOp("forecast_runs", ForecastRun, in_ids(ForecastRun.id, ids["forecast_runs"]), ForecastRun.id),
        CleanupOp("serial_numbers", SerialNumber, in_ids(SerialNumber.id, ids["serial_numbers"]), SerialNumber.id),
        CleanupOp("inventory_batches", InventoryBatch, in_ids(InventoryBatch.id, ids["inventory_batches"]), InventoryBatch.id),
        CleanupOp("inventory", Inventory, in_ids(Inventory.id, ids["inventory"]), Inventory.id),
        CleanupOp("stock_movements", StockMovement, in_ids(StockMovement.id, ids["stock_movements"]), StockMovement.id),
        CleanupOp("product_suppliers", ProductSupplier, in_ids(ProductSupplier.id, ids["product_suppliers"]), ProductSupplier.id),
        CleanupOp(
            "product_warehouse_settings",
            ProductWarehouseSetting,
            in_ids(ProductWarehouseSetting.id, ids["product_warehouse_settings"]),
            ProductWarehouseSetting.id,
        ),
        CleanupOp("customer_product_prices", CustomerProductPrice, in_ids(CustomerProductPrice.id, ids["customer_product_prices"]), CustomerProductPrice.id),
        CleanupOp("product_base_prices", ProductBasePrice, in_ids(ProductBasePrice.id, ids["product_base_prices"]), ProductBasePrice.id),
        CleanupOp("customer_contacts", CustomerContact, in_ids(CustomerContact.id, ids["customer_contacts"]), CustomerContact.id),
        CleanupOp("customer_locations", CustomerLocation, in_ids(CustomerLocation.id, ids["customer_locations"]), CustomerLocation.id),
        CleanupOp("documents", Document, in_ids(Document.id, ids["documents"]), Document.id),
        CleanupOp("user_dashboard_configs", UserDashboardConfig, in_ids(UserDashboardConfig.id, ids["user_dashboard_configs"]), UserDashboardConfig.id),
        CleanupOp("user_ui_preferences", UserUiPreference, in_ids(UserUiPreference.id, ids["user_ui_preferences"]), UserUiPreference.id),
        CleanupOp("role_dashboard_policies", RoleDashboardPolicy, in_ids(RoleDashboardPolicy.id, ids["role_dashboard_policies"]), RoleDashboardPolicy.id),
        CleanupOp("integration_clients", IntegrationClient, in_ids(IntegrationClient.id, ids["integration_clients"]), IntegrationClient.id),
        CleanupOp(
            "user_permission_overrides",
            User.__table__.metadata.tables["user_permission_overrides"],
            in_ids(User.__table__.metadata.tables["user_permission_overrides"].c.user_id, ids["users"]),
            None,
        ),
        CleanupOp(
            "role_permissions",
            role_permissions,
            in_ids(role_permissions.c.role_id, ids["roles"]),
            None,
        ),
        CleanupOp(
            "user_roles",
            user_roles,
            where_any(
                in_ids(user_roles.c.user_id, ids["users"]),
                in_ids(user_roles.c.role_id, ids["roles"]),
            ),
            None,
        ),
        CleanupOp("roles", Role, in_ids(Role.id, ids["roles"]), Role.id),
        CleanupOp("customers", Customer, in_ids(Customer.id, ids["customers"]), Customer.id),
        CleanupOp("suppliers", Supplier, in_ids(Supplier.id, ids["suppliers"]), Supplier.id),
        CleanupOp("products", Product, in_ids(Product.id, ids["products"]), Product.id),
        CleanupOp("product_groups", ProductGroup, in_ids(ProductGroup.id, ids["product_groups"]), ProductGroup.id),
        CleanupOp("bin_locations", BinLocation, in_ids(BinLocation.id, ids["bin_locations"]), BinLocation.id),
        CleanupOp("warehouse_zones", WarehouseZone, in_ids(WarehouseZone.id, ids["warehouse_zones"]), WarehouseZone.id),
        CleanupOp("warehouses", Warehouse, in_ids(Warehouse.id, ids["warehouses"]), Warehouse.id),
        CleanupOp("users", User, in_ids(User.id, ids["users"]), User.id),
    ]

    return ops


def print_warning(database_url: str, mode: str) -> None:
    lowered = database_url.lower()
    risk_terms = ("prod", "production", "rds.amazonaws.com", "azure.com", "gcp")
    has_risk = any(term in lowered for term in risk_terms)

    print(f"Target database: {database_url}")
    if mode == "apply":
        print("WARNING: APPLY mode permanently deletes matched test records.")
        print("WARNING: Ensure backup/restore point exists before execution.")
    if has_risk:
        print("WARNING: database URL appears production-like. Re-check before apply.")


def main() -> None:
    args = parse_args()
    settings = get_settings()

    print_warning(settings.database_url, args.mode)

    engine = create_engine(settings.database_url, future=True, pool_pre_ping=True)

    with Session(engine) as session:
        ids = collect_ids(session)
        ops = build_operations(ids)

        report_rows: list[tuple[CleanupOp, int, list[int]]] = []
        total_rows = 0
        for op in ops:
            count = count_rows(session, op.table, op.where_clause)
            samples = sample_ids(session, op.id_column, op.where_clause, args.sample_size) if op.id_column else []
            report_rows.append((op, count, samples))
            total_rows += count

        print("\nCleanup candidate summary")
        print("-------------------------")
        for op, count, samples in report_rows:
            if count == 0:
                continue
            sample_text = f" sample_ids={samples}" if samples else ""
            print(f"{op.label}: count={count}{sample_text}")
        print(f"TOTAL matched rows: {total_rows}")

        if args.mode == "dry-run":
            print("\nDry-run complete. No data was modified.")
            session.rollback()
            return

        for op, count, _ in report_rows:
            if count == 0:
                continue
            session.execute(delete(op.table).where(op.where_clause))

        session.commit()
        print("\nApply complete. Deleted rows:")
        for op, count, _ in report_rows:
            if count == 0:
                continue
            print(f"{op.label}: deleted={count}")


if __name__ == "__main__":
    main()
